---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[twemproxy::default]
    attributes:
      twemproxy:
        config:
          alpha:
            listen: 127.0.0.1:22121
            hash: fnv1a_64
            distribution: ketama
            auto_eject_hosts: true
            redis: true
            server_retry_timeout: 2000
            server_failure_limit: 1
            servers:
            - 127.0.0.1:6379:1
